apiVersion: v1
kind: Service
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{ .Values.namespace }}
spec:
  ports:
  {{- with .Values.service }}
  - name: {{ .port }}-{{ .targetPort }}
    port: {{ .port }}
    protocol: {{ .protocol }}
    targetPort: {{ .targetPort }}
  selector:
    app: techtrends
  type: {{ .type }}
  {{- end }}